# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [110]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [111]:
print(np.__version__)

1.22.4


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [112]:
#Array of 2 blocks, 3 rows and 5 columns
#Option 1: Random floats

a = np.random.random((2,3,5))
a


array([[[0.4551726 , 0.28276974, 0.7900479 , 0.78733144, 0.47981212],
        [0.39330179, 0.15224057, 0.20415681, 0.35753324, 0.56567009],
        [0.15781266, 0.26562872, 0.5758204 , 0.9464613 , 0.89684903]],

       [[0.69091408, 0.54504794, 0.80189804, 0.09693386, 0.70696964],
        [0.37425019, 0.17472472, 0.59173969, 0.57518836, 0.5286985 ],
        [0.49858334, 0.97107954, 0.11680451, 0.94478059, 0.38983961]]])

In [113]:
#Option 2, This sets a range when attributes like low and high are given.
#random.randint(low, high=None, size=None, dtype=int)
a = np.random.randint(2,high=21, size=(2, 3, 5))
a

array([[[14, 18, 15, 17, 15],
        [ 6, 13,  4, 12, 17],
        [17, 12,  7,  9,  5]],

       [[11, 12, 16,  6, 18],
        [10,  8,  3,  4, 13],
        [15, 14,  2, 15,  4]]])

In [114]:
#Option 3: Create an array of the given shape and populate it with random samples from a uniform distribution over 0, 1.
a = np.random.rand(2, 3, 5)
a.shape

(2, 3, 5)


### 4. Print a.


In [115]:
a

array([[[0.83675814, 0.40840303, 0.52548908, 0.7630673 , 0.95323727],
        [0.68639148, 0.83531208, 0.44854286, 0.93451298, 0.58443391],
        [0.8564917 , 0.90607017, 0.35838332, 0.65926705, 0.44732404]],

       [[0.16162695, 0.75943228, 0.21969375, 0.28372028, 0.57734944],
        [0.13773785, 0.08572773, 0.5888916 , 0.28758355, 0.08656903],
        [0.67714239, 0.81198517, 0.6314591 , 0.86595864, 0.57711459]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [116]:
#Create an array of ones of 5 blocks, 2 rows and 3 columns

b = np.ones((5,2,3))



### 6. Print b.


In [117]:
b


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [118]:
if len(a) == len(b): 
    print(True)
else: 
    print(False)

False


In [119]:
len(a)

2

In [120]:
len(b)

5

This result will always give different values because a consists of 2 sublists, while b consists of 5 sublists. To find the actual size we will have to iterate over all the items in the lists. 

In [121]:
#True size of a in python
#A is a subset of 2 lists, each with 3 sublists
size_b = 0
for i in b: 
    for j in i:
        for k in j: 
            size_b+=1
print(size_b)

30


In [122]:
#True size of b in python
#A is a subset of 5 lists each with 2 sublists
size_a = 0
for i in a: 
    for j in i: 
        for k in j:
            size_a+=1
print(size_a)

30



### 8. Are you able to add a and b? Why or why not?


The shape of each array is different, so there is no way to add them as they are because the indexes of each value do not correspond from a to b.



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [123]:
a.shape

(2, 3, 5)

In [124]:
b.shape

(5, 2, 3)

In [125]:
# if in the b array: 5x2x3 the axis where (0,1,2) then the transpose function shapes the axis to be (1,2,0) or 2x3x5
c = np.transpose(b,(1,2,0))
c.shape

(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [126]:
d= a+c
d

array([[[1.83675814, 1.40840303, 1.52548908, 1.7630673 , 1.95323727],
        [1.68639148, 1.83531208, 1.44854286, 1.93451298, 1.58443391],
        [1.8564917 , 1.90607017, 1.35838332, 1.65926705, 1.44732404]],

       [[1.16162695, 1.75943228, 1.21969375, 1.28372028, 1.57734944],
        [1.13773785, 1.08572773, 1.5888916 , 1.28758355, 1.08656903],
        [1.67714239, 1.81198517, 1.6314591 , 1.86595864, 1.57711459]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [127]:
print(f"a array:\n {a} \n\n d array:\n {d}")


a array:
 [[[0.83675814 0.40840303 0.52548908 0.7630673  0.95323727]
  [0.68639148 0.83531208 0.44854286 0.93451298 0.58443391]
  [0.8564917  0.90607017 0.35838332 0.65926705 0.44732404]]

 [[0.16162695 0.75943228 0.21969375 0.28372028 0.57734944]
  [0.13773785 0.08572773 0.5888916  0.28758355 0.08656903]
  [0.67714239 0.81198517 0.6314591  0.86595864 0.57711459]]] 

 d array:
 [[[1.83675814 1.40840303 1.52548908 1.7630673  1.95323727]
  [1.68639148 1.83531208 1.44854286 1.93451298 1.58443391]
  [1.8564917  1.90607017 1.35838332 1.65926705 1.44732404]]

 [[1.16162695 1.75943228 1.21969375 1.28372028 1.57734944]
  [1.13773785 1.08572773 1.5888916  1.28758355 1.08656903]
  [1.67714239 1.81198517 1.6314591  1.86595864 1.57711459]]]


The array of ones was added to the a array, this is why all values in a are a+1.


### 12. Multiply a and c. Assign the result to e.


In [128]:
e = a*c


In [129]:
e

array([[[0.83675814, 0.40840303, 0.52548908, 0.7630673 , 0.95323727],
        [0.68639148, 0.83531208, 0.44854286, 0.93451298, 0.58443391],
        [0.8564917 , 0.90607017, 0.35838332, 0.65926705, 0.44732404]],

       [[0.16162695, 0.75943228, 0.21969375, 0.28372028, 0.57734944],
        [0.13773785, 0.08572773, 0.5888916 , 0.28758355, 0.08656903],
        [0.67714239, 0.81198517, 0.6314591 , 0.86595864, 0.57711459]]])



### 13. Does e equal to a? Why or why not?


In [130]:
np.array_equal(e,a)


True

Yes, the result of e was the multiplication of a with unity.



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [131]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(f"Max: {d_max} \nMin: {d_min} \nMean: {d_mean}")

Max: 1.9532372691525732 
Min: 1.0857277337736833 
Mean: 1.5651892258341762



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [132]:
#Creating an empty array: Return a new array of given shape and type, without initializing entries
f= np.empty((2,3,5))
f


array([[[0.83675814, 0.40840303, 0.52548908, 0.7630673 , 0.95323727],
        [0.68639148, 0.83531208, 0.44854286, 0.93451298, 0.58443391],
        [0.8564917 , 0.90607017, 0.35838332, 0.65926705, 0.44732404]],

       [[0.16162695, 0.75943228, 0.21969375, 0.28372028, 0.57734944],
        [0.13773785, 0.08572773, 0.5888916 , 0.28758355, 0.08656903],
        [0.67714239, 0.81198517, 0.6314591 , 0.86595864, 0.57711459]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [133]:
#This could also be done by overwriting the values just with indexing
#when f = d, then f[condition]=new value

In [140]:
#Populate f with d
#Update for the values in f
#Conditions 
f = np.where(((d > d_min) & (d < d_mean)), 25 , f)
f = np.where(((d > d_mean) & (d < d_max)), 75 , f)
f = np.where((d == d_mean),50 , f)
f = np.where((d == d_min),0 , f)
f = np.where((d == d_max),100 , f)
f


array([[[ 75.,  25.,  25.,  75., 100.],
        [ 75.,  75.,  25.,  75.,  75.],
        [ 75.,  75.,  25.,  75.,  25.]],

       [[ 25.,  75.,  25.,  25.,  75.],
        [ 25.,   0.,  75.,  25.,  25.],
        [ 75.,  75.,  75.,  75.,  75.]]])





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [141]:
print(f"d array:\n {d} \n\n f array:\n {f}")

d array:
 [[[1.83675814 1.40840303 1.52548908 1.7630673  1.95323727]
  [1.68639148 1.83531208 1.44854286 1.93451298 1.58443391]
  [1.8564917  1.90607017 1.35838332 1.65926705 1.44732404]]

 [[1.16162695 1.75943228 1.21969375 1.28372028 1.57734944]
  [1.13773785 1.08572773 1.5888916  1.28758355 1.08656903]
  [1.67714239 1.81198517 1.6314591  1.86595864 1.57711459]]] 

 f array:
 [[[ 75.  25.  25.  75. 100.]
  [ 75.  75.  25.  75.  75.]
  [ 75.  75.  25.  75.  25.]]

 [[ 25.  75.  25.  25.  75.]
  [ 25.   0.  75.  25.  25.]
  [ 75.  75.  75.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [160]:
g= np.char.replace(
    np.char.replace(
        np.char.replace(
            np.char.replace(
                np.char.replace(f.astype(str) ,'100.0','E'),
            '25.0','B'),
        '50.0','C'),
    '75.0','D'),
'0.0','A'),
g

(array([[['D', 'B', 'B', 'D', 'E'],
         ['D', 'D', 'B', 'D', 'D'],
         ['D', 'D', 'B', 'D', 'B']],
 
        [['B', 'D', 'B', 'B', 'D'],
         ['B', 'A', 'D', 'B', 'B'],
         ['D', 'D', 'D', 'D', 'D']]], dtype='<U1'),)